apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  namespace: default
  name: jobair
  annotations:
    original-service-name: jobair
spec:
  predictor:
    minReplicas: 0
    maxReplicas: 1
    containers:
    - args:
      - --port
      - '8080'
      - --model
      - /mnt/models
      command:
      - python3
      - -m
      - vllm.entrypoints.openai.api_server
      env:
      - name: STORAGE_URI
        value: pvc://jobair-pvc/model_files/
      image: docker.io/kserve/vllmserver:latest
      imagePullPolicy: IfNotPresent
      name: kserve-container
      resources:
        limits:
          cpu: 32
          memory: 30Gi
          nvidia.com/gpu: 1
        requests:
          cpu: 10
          memory: 10Gi
          nvidia.com/gpu: 1
