apiVersion: v1
kind: Pod
metadata:
  name: model-store-pod-job1
spec:
  volumes:
  - name: model-store
    persistentVolumeClaim:
      claimName: job1-pvc
  containers:
  - name: model-store
    image: ubuntu
    command:
    - sleep
    args:
    - infinity
    volumeMounts:
    - mountPath: /mnt/models
      name: model-store
    resources:
      limits:
        memory: 10Gi
        cpu: 10
