apiVersion: v1
kind: PersistentVolume
metadata:
  name: job1-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: assests/temp/deployment/Gyan/OPT-350M/Project1
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: job1-pvc
    namespace: knative-serving
  reclaimPolicy: Retain
