apiVersion: v1
kind: PersistentVolume
metadata:
  name: jobair-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: assests/temp/deployment/Gyan/OPT-350M/AirPuri
